AWSTemplateFormatVersion: "2010-09-09"
Description:
Resources:
  DummyServer:
    Type: "AWS::EC2::NatGateway"
    Properties:
      AllocationId:
        Fn::GetAtt:
          - EIP
          - AllocationId
      SubnetId:
        Ref: Subnet
      ImageId: ""
